apiVersion: v1
kind: Namespace
metadata:
  name: ns-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-2
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-3
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-4
