apiVersion: v1
kind: Service
metadata:
  name: svc-1
  namespace: ns-1
spec:
  selector:
    app: pod
  ports:
  - port: 9000
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-2
  namespace: ns-2
spec:
  selector:
    app: pod
  ports:
  - port: 9000
    targetPort: 8080
---
